name: raster-pipeline
channels:
- defaults
dependencies:
- python=3.7.*
- cython
- numpy
- ipython
- libspatialindex
- libgdal=2.3.3
- gdal=2.3.3
- pip
- pip:
  - numpy>=1.18.5
  - GDAL==2.3.3
  - pyproj
  - rasterio>=1.1.5
